version: '3.8'

services:
  # 1. СЕРВІС ЧЕРГИ ТА КЕШУ
  redis:
    image: redis:6-alpine
    container_name: redis_queue_cache
    networks:
      - internal_network
    command: redis-server --appendonly yes 

  # 2. СЕРВІС СТІЙКОГО СХОВИЩА (POSTGRESQL)
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Стійкий Volume для БД
    networks:
      - internal_network

  # 3. СЕРВІС API-ШЛЮЗУ 
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: image_api_gateway
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - redis
      - postgres 
    networks:
      - internal_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      # ЗМІННІ СЕРЕДОВИЩА ДЛЯ POSTGRES
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_DBNAME=jobs_db

  # 4. СЕРВІС ОБРОБКИ 
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: image_worker_service
    volumes:
      - ./storage:/app/storage
    depends_on:
      - redis
      - postgres 
    networks:
      - internal_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      # ЗМІННІ СЕРЕДОВИЩА ДЛЯ POSTGRES
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_DBNAME=jobs_db
      
# 5. СЕРВІС ВІЗУАЛІЗАЦІЇ (Grafana)
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal_network
    depends_on:
      - prometheus
networks:
  internal_network:
    driver: bridge

volumes:
  postgres_data: # Визначення Volume для Postgre