# Deployment для Worker Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-deployment
  labels:
    app: worker-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker-service
        image: butsenkoiv/image-worker-service:v2
        imagePullPolicy: Always 
        
        # Змінні середовища для підключення до Redis
        env:
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        
        # Ресурси
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
---
# Service для Worker Service (Залишаємо без змін)
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker-service
spec:
  selector:
    app: worker-service
  ports:
    - protocol: TCP
      port: 8081 # Порт Service
      targetPort: 8081 # Порт контейнера
  type: ClusterIP